[questioncode]
old_name = "questioncode"
Deduced_Data_Type = "int64"

[period]
old_name = "period"
Deduced_Data_Type = "int64"

[reference]
old_name = "reference"
Deduced_Data_Type = "int64"

[adjustedresponse]
old_name = "adjustedresponse"
Deduced_Data_Type = "float64"

[response]
old_name = "response"
Deduced_Data_Type = "float64"

[frosic2007]
old_name = "frosic2007"
Deduced_Data_Type = "int64"

[froempment]
old_name = "froempment"
Deduced_Data_Type = "int64"

[frotover]
old_name = "frotover"
Deduced_Data_Type = "float64"

[entname1]
old_name = "entname1"
Deduced_Data_Type = "object"

[cell_no]
old_name = "cell_no"
Deduced_Data_Type = "int64"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "int64"

[form_type_spp]
old_name = "form_type_spp"
Deduced_Data_Type = "int64"

[imputation_flags_adjustedresponse]
old_name = "imputation_flags_adjustedresponse"
Deduced_Data_Type = "object"

[status]
old_name = "status"
Deduced_Data_Type = "object"

[statusencoded]
old_name = "statusencoded"
Deduced_Data_Type = "float64"

[live_adjustedresponse]
old_name = "live_adjustedresponse"
Deduced_Data_Type = "float64"

[converted_frotover]
old_name = "converted_frotover"
Deduced_Data_Type = "float64"

[ni_gb_cell_number]
old_name = "ni_gb_cell_number"
Deduced_Data_Type = "float64"

[imputation_class]
old_name = "imputation_class"
Deduced_Data_Type = "float64"

[backdata_adjustedresponse]
old_name = "backdata_adjustedresponse"
Deduced_Data_Type = "float64"

[backdata_flags_adjustedresponse]
old_name = "backdata_flags_adjustedresponse"
Deduced_Data_Type = "float64"

[adjustedresponse_man]
old_name = "adjustedresponse_man"
Deduced_Data_Type = "float64"

[f_match_adjustedresponse]
old_name = "f_match_adjustedresponse"
Deduced_Data_Type = "object"

[b_match_adjustedresponse]
old_name = "b_match_adjustedresponse"
Deduced_Data_Type = "object"

[f_link_adjustedresponse]
old_name = "f_link_adjustedresponse"
Deduced_Data_Type = "float64"

[default_link_f_match_adjustedresponse]
old_name = "default_link_f_match_adjustedresponse"
Deduced_Data_Type = "object"

[b_link_adjustedresponse]
old_name = "b_link_adjustedresponse"
Deduced_Data_Type = "float64"

[default_link_b_match_adjustedresponse]
old_name = "default_link_b_match_adjustedresponse"
Deduced_Data_Type = "object"

[construction_link]
old_name = "construction_link"
Deduced_Data_Type = "float64"

[default_link_flag_construction_matches]
old_name = "default_link_flag_construction_matches"
Deduced_Data_Type = "object"

[f_match_adjustedresponse_count]
old_name = "f_match_adjustedresponse_count"
Deduced_Data_Type = "float64"

[b_match_adjustedresponse_count]
old_name = "b_match_adjustedresponse_count"
Deduced_Data_Type = "float64"

[flag_construction_matches_count]
old_name = "flag_construction_matches_count"
Deduced_Data_Type = "float64"

[pre_derived_adjustedresponse]
old_name = "pre_derived_adjustedresponse"
Deduced_Data_Type = "float64"

[constrain_marker]
old_name = "constrain_marker"
Deduced_Data_Type = "object"

[pre_constrained_adjustedresponse]
old_name = "pre_constrained_adjustedresponse"
Deduced_Data_Type = "float64"

[imputed_and_derived_flag]
old_name = "imputed_and_derived_flag"
Deduced_Data_Type = "object"
