[reference]
old_name = "reference"
Deduced_Data_Type = "int64"

[period]
old_name = "period"
Deduced_Data_Type = "int64"

[frosic2007]
old_name = "frosic2007"
Deduced_Data_Type = "int64"

[classification]
old_name = "classification"
Deduced_Data_Type = "int64"

[cell_no]
old_name = "cell_no"
Deduced_Data_Type = "int64"

[frotover]
old_name = "frotover"
Deduced_Data_Type = "float64"

[froempment]
old_name = "froempment"
Deduced_Data_Type = "int64"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "int64"

[imputed_and_derived_flag]
old_name = "imputed_and_derived_flag"
Deduced_Data_Type = "object"

[questioncode]
old_name = "questioncode"
Deduced_Data_Type = "int64"

[adjustedresponse]
old_name = "adjustedresponse"
Deduced_Data_Type = "float64"

[statusencoded]
old_name = "statusencoded"
Deduced_Data_Type = "float64"

[design_weight]
old_name = "design_weight"
Deduced_Data_Type = "float64"

[calibration_factor]
old_name = "calibration_factor"
Deduced_Data_Type = "float64"

[outlier_weight]
old_name = "outlier_weight"
Deduced_Data_Type = "float64"

["total weight (A*G*O)"]
old_name = "total weight (A*G*O)"
Deduced_Data_Type = "float64"

["weighted adjusted value"]
old_name = "weighted adjusted value"
Deduced_Data_Type = "float64"

[imputation_flags_adjustedresponse]
old_name = "imputation_flags_adjustedresponse"
Deduced_Data_Type = "object"

[imputation_class]
old_name = "imputation_class"
Deduced_Data_Type = "float64"

[f_link_adjustedresponse]
old_name = "f_link_adjustedresponse"
Deduced_Data_Type = "float64"

[default_link_f_match_adjustedresponse]
old_name = "default_link_f_match_adjustedresponse"
Deduced_Data_Type = "object"

[b_link_adjustedresponse]
old_name = "b_link_adjustedresponse"
Deduced_Data_Type = "float64"

[default_link_b_match_adjustedresponse]
old_name = "default_link_b_match_adjustedresponse"
Deduced_Data_Type = "object"

[construction_link]
old_name = "construction_link"
Deduced_Data_Type = "float64"

[flag_construction_matches_count]
old_name = "flag_construction_matches_count"
Deduced_Data_Type = "float64"

[default_link_flag_construction_matches]
old_name = "default_link_flag_construction_matches"
Deduced_Data_Type = "object"

[constrain_marker]
old_name = "constrain_marker"
Deduced_Data_Type = "object"

[b_match_adjustedresponse_count]
old_name = "b_match_adjustedresponse_count"
Deduced_Data_Type = "float64"

[f_match_adjustedresponse_count]
old_name = "f_match_adjustedresponse_count"
Deduced_Data_Type = "float64"
